version: '3'

services:
  master:
    build: ./master
    ports:
      - "8000:8000"
    volumes:
      - master-db:/app
    restart: always
  worker:
    build: ./worker
    restart: always
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 300m
    depends_on:
      - master


volumes:
  master-db:

