version: '3'

services:
  auto-render-master:
    build: ./master
    container_name: auto-render
    volumes:
      - master-db:/app
    restart: always
  auto-render-worker:
    build: ./worker
    restart: always
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 300m
    depends_on:
      - auto-render-master


volumes:
  master-db:

