version: '3'

services:
  auto-render-master:
    build: ./master
    container_name: auto-render
    volumes:
      - master-db:/app
    restart: always
    environment:
      - LUST_HOST=https://images.crunchy.gg/content
      - LUST_ADMIN_HOST=http://lust:7070
  auto-render-worker:
    build: ./worker
    restart: always
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 400m
    links:
      - "auto-render-master:auto-render"
    depends_on:
      - auto-render-master

networks:
  default:
    external: true
    name: crunchy_net

volumes:
  master-db:

